### PR TITLE
Fix type of retry option: `retry` can be boolean or a number

### PR DESCRIPTION
**Pull request by Antti**
According to the sidekiq docs, `sidekiq_options` `retry` param can be either boolean or a number.

Change the param of the retry argument to be a JsonValue for now, as it's a convenient wrapper over different basic types

### CODE REVIEW

**Comment by film42** [comment]
Thanks for the PR. Good find!

I think `JsonValue` is convenient but a little too broad. Let me see if I can push a change up that captures this intent though.

**Comment by film42** [comment]
@Antti would you mind allowing maintainer push to your fork?

I refactored from JsonValue (which was a very helpful refresher so thank you for the PR) to a new RetryOpts type with  a backwards compatible retry() method that now supports:

```rust
opts()
  // old way
  .retry(true).retry(false)
  // now usize is supported
  .retry(42)
  // and the new enum is available too
  .retry(RetryOpts::Yes).retry(RetryOpts::Never).retry(RetryOpts::Max(42)
```

I have a branch up here that I can open a new PR with but would love your thoughts: https://github.com/film42/sidekiq-rs/compare/gt/retry_opts?expand=1

I would like to add a few tests but I'm on a flight at the moment and I'll be out of internet range soon so wanted to get this up for the moment.

**Comment by Antti** [comment]
@film42 I think it looks good, certainly better than a plain JsonValue!

**Comment by film42** [comment]
Sweet. I need to do a few more small things before cutting a new release.

**Comment by film42** [comment]
Thanks for getting this one started, @Antti ! ❤️ ❤️ ❤️

**Pull request merged**
